### ISSUE TITLE
Changing color/hue

### ISSUE THREAD

**Issue by laurilubi** [AlCalzone/node-tradfri-client#11]
I am now controlling on-off and dimmer of the lights, sending API commands directly to the lights. Btw using `tradfri.operateGroup()` does not work here, returns `false `and nothing happens.

I am abit confused if I should use `setColor()`, `setColorTemperature()`, `setHue()` or `setSaturation()` for my lights? I have:
```
spectrum white, TRADFRI bulb E27 WS opal 980lm
spectrum none, TRADFRI bulb E27 opal 1000lm
```
I have tested with different values from predefined-colors.ts with no success yet.

**Comment by AlCalzone** [comment]
> Btw using `tradfri.operateGroup()` does not work here, returns `false` and nothing happens.

Internally, that method takes the group object you provide, creates a copy and sets the parameters you want to update. Then it compares the copy with the original and only sends the changed properties to the gateway. If the two objects were identical, it sends nothing and returns `false`.

You can work around that by explicitly modifying the group object so its properties will change when merged with the group operation. In my application, I react to the state changes of the lights. When a property is identical on all lights, I set that value on the group object. When it's not, I set the corresponding value on the group object to `null`.

Regarding your lights:  
On the bulb with spectrum `white`, only `setColorTemperature()` should work, the others should throw an error. For the other bulb, none of those methods should work since it has no spectrum. 
The methods `setColor()`, `setHue()` and `setSaturation()` only work on RGB bulbs.

I recently fixed a bug (9de7d9a) where the tests for those capabilities were reversed. If you haven't already, please update to v0.5.0

**Comment by laurilubi** [comment]
Regarding the lights:
I think the confusion came from what I found in predefined-colors.ts:
`export const whiteSpectrumTemp = [250, 370, 454];`
So i tried with these values. It also matches that there are 3 color modes for these lamps in the Ikea app.

I saw now that the values are supposed to be 0 - 100. But I only manage to change the light to "focus" (the most white of the three). This happens regardless the value I use. Tested with 0, 10, 20, 63, 70, 100.

When I read back the values while changing via Ikea controller I see the following:
```
0 - white
63 - yellow
100 - reddish
```
I was on version 0.5.0 already :)

**Comment by AlCalzone** [comment]
I see. Those lines are leftovers from when I was experimenting with the RGB color support.

Its weird that you're not able to set the intermediate values. I can set them and I see small changes in color when I do. Mind sharing some code?

**Comment by AlCalzone** [comment]
Apparently, there's something wrong with `setColorTemperature()` and the similar functions (#13). I'm investigating.

**Comment by AlCalzone** [comment]
Can you please test again with v0.5.3?

**Comment by laurilubi** [comment]
I have been busy the last days but tested now with v0.5.3. Works like charm! Thank you!

Might be good to add a comment to `light.setColorTemperature()` that values 0, 63 and 100 are supported on white spectrum Ikea lights. Or possibly refer to `whiteSpectrumHex` in `predefined-colors.ts`?

**Comment by laurilubi** [comment]
> Mind sharing some code?

This is what I am developing :)
https://github.com/laurilubi/ikea-tradfri

**Comment by AlCalzone** [comment]
> Might be good to add a comment to `light.setColorTemperature()` that values 0, 63 and 100 are supported on white spectrum Ikea lights.

Actually, the whole range from 0..100 should be supported.
