### ISSUE TITLE
No group updates

### ISSUE THREAD

**Issue by realjax** [AlCalzone/node-tradfri-client#217]
Hello,

I use `tradfri.observeGroupsAndScenes(): Promise<void>;`  in order to observe groups. 
But the "group updated" callback is not called when the group is switched on/off ( using the ikea tradfri app) or when the brightness ( dimmer) values are changed.

**Comment by AlCalzone** [comment]
I just checked that because I was not sure. This is most likely also related to your other group questions. The callback is indeed not called when the group is switched, because the gateway only reports changes to every single bulb. 
However it is being called, when you change the group itself:
* rename it
* remove devices
* add devices
* redefine scenes

**Comment by realjax** [comment]
Done, see [PR](https://github.com/AlCalzone/node-tradfri-client/pull/223)

**Comment by AlCalzone** [comment]
Closed by #223
