### ISSUE TITLE
toggle() on group not working

### ISSUE THREAD

**Issue by realjax** [AlCalzone/node-tradfri-client#218]
Calling toggle() on a group only toggles a light off, you can not toggle() it back on again unless toggle(true) is used.

**Comment by AlCalzone** [comment]
That is the intended behavior. It is subtle, but also documented.

Gropus:
https://github.com/AlCalzone/node-tradfri-client#group
> toggle(value: boolean) - Sets all lights' state to the given value.

Lights:
https://github.com/AlCalzone/node-tradfri-client#light
> toggle([value: boolean]) - Toggles the light's state to the given value or the opposite of its current state.

The reason is that the gateway has no notion of a group's state. It can issue commands to groups, but does not report the group state back. So I have no easy way of knowing which state the group is in.

**Comment by realjax** [comment]
Ah I see. Thanks for clearing that up.  

AlCalzone <notifications@github.com> schreef op 21 juli 2019 19:12:16 CEST:

**Comment by realjax** [comment]
Still leaves me confused. What is the point of having toggle(true) and toggle(false) when there's also an turnOn() and turnOff() method?

**Comment by AlCalzone** [comment]
That comes from iobroker.tradfri, which simulates having states for groups by aggregating the state of all bulbs. The on/off state is represented with a boolean, so I wanted a simple way to operate based on the current state - hence the toggle method.
It's not super necessary, since I could also do `state ? turnOff() : turnOn()`, but I felt that its more in line with the lights this way.
