### ISSUE TITLE
Dimmer values on groups incorrect

### ISSUE THREAD

**Issue by realjax** [AlCalzone/node-tradfri-client#219]
The group object received by the callback has a dimmer value of 0 or 100 but never represent the values of the group.

**Comment by AlCalzone** [comment]
This is also related to the gateway not reporting the state of groups (see #218). It can be worked around by querying the state of all the group's bulbs. Preferably also debounce the result since the bulbs are updated sequentially. For an idea how to do that, you can start there:
https://github.com/AlCalzone/ioBroker.tradfri/blob/87c432bd36d639a0c8222c61af1544b1cc0d3d1b/src/modules/groups.ts#L208

**Comment by realjax** [comment]
Thanks. I was exploring a similar solution 😊 

AlCalzone <notifications@github.com> schreef op 21 juli 2019 19:14:30 CEST:
