### ISSUE TITLE
Is there currently any chance to read a sensor/switch/group current onOff value?

### ISSUE THREAD

**Issue by jonasborn** [AlCalzone/node-tradfri-client#318]
Hi, I'm currently searching for any solution to get the current onOff value of sensor/switch/group. On any way, I would suggest to add a note to the documentation.

**Comment by AlCalzone** [comment]
For groups you can take a look at the ioBroker Tradfri adapter:
https://github.com/AlCalzone/ioBroker.tradfri/blob/31794b469c6ae84831186228f64959f4168cffd2/src/modules/groups.ts#L223

Motion sensors are not supported by this library, since the gateway sends no information about them.

For plugs it should work just like with bulbs, using `observeDevice`.

**Comment by jonasborn** [comment]
Thanks, will have a look on it.
In the mean time, I already changed a part of my network to use zigbee2mqtt. Had to built up hass.io to get Google Home working again. Takes some time to configure, but its working.
(Just in case somebody got the same issue)

**Comment by AlCalzone** [comment]
Alright, closing then. Feel free to reopen if necessary.
