### ISSUE TITLE
Correctly iterating bulbs

### ISSUE THREAD

**Issue by yocal** [AlCalzone/node-tradfri-client#494]
I iterate over 25 bulbs and set a color to each one.  Sometimes the bulb seems to ignore the request completely even though the promise for `operateLight` returns true.

Are there some kind of buffer that limits the rate I can send commands at?

**Comment by AlCalzone** [comment]
I've had reports in the past where commands got lost when they were sent too quickly, especially when there's a transition time involved.

Sadly that's nothing we can handle, as the problem is either in the gateway firmware or in the communication between gateway and the bulbs.

Your best bet is to use groups and send as few commands as possible.

**Comment by yocal** [comment]
Challenge is I need to change each cloud to a different color - and according to the documentation it doesn't support setting colors on groups. 

I've implemented a 100ms delay between the requests and that seem to fix it. A bit of a hacky solution, but I mean, what can you do. When you change the color of a group via the app, they seem to do it on each bulb individually as well, so I guess they weren't able to solve it themselves :P
